# Generated by Django 3.1.3 on 2021-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210324_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='brief',
            field=models.CharField(max_length=200, null=True, verbose_name='说明'),
        ),
    ]
