# Generated by Django 3.1.3 on 2021-02-22 15:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210220_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classname', models.CharField(max_length=20, verbose_name='商品分类名')),
                ('brief', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品分类简介')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('unit_name', models.CharField(max_length=10, verbose_name='单位名')),
            ],
            options={
                'verbose_name': '商品单位',
                'verbose_name_plural': '商品单位',
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku_name', models.CharField(max_length=20, verbose_name='商品SKU名称')),
                ('brief', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('logo', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='封面照片')),
                ('is_on_sale', models.BooleanField(choices=[(False, '不上架'), (True, '上架')], default=False, verbose_name='商品是否上架')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.category', verbose_name='商品分类ID')),
                ('goods_spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsspu', verbose_name='商品的SPU')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.unit', verbose_name='商品单位')),
            ],
            options={
                'verbose_name': '商品SKU管理',
                'verbose_name_plural': '商品SKU管理',
                'db_table': 'goods_SKU',
            },
        ),
    ]
