# Generated by Django 3.1.3 on 2021-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_category_goodssku_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品分类管理', 'verbose_name_plural': '商品分类管理'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='classname',
            new_name='cate_name',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='排序'),
        ),
    ]
