# Generated by Django 3.1.3 on 2020-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spuser',
            name='head',
            field=models.ImageField(default='head/memtx.png', upload_to='head/%Y%m', verbose_name='用户头像'),
        ),
    ]
