# Generated by Django 3.1.3 on 2021-03-12 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_spuser_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请填写正确的手机号码')], verbose_name='收货人电话')),
                ('hcity', models.CharField(max_length=100, verbose_name='省')),
                ('hproper', models.CharField(blank=True, max_length=100, null=True, verbose_name='市')),
                ('harea', models.CharField(blank=True, max_length=100, null=True, verbose_name='区')),
                ('brief', models.CharField(max_length=255, verbose_name='详细地址')),
                ('isDefault', models.BooleanField(blank=True, default=False, verbose_name='是否设置为默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.spuser', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '收货地址管理',
                'verbose_name_plural': '收货地址管理',
                'db_table': 'user_address',
            },
        ),
    ]
